src/main/java/pl/pb/shop_cli/model/Discount.java
package pl.pb.shop_cli.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Discount extends AbstractModel {
    private String code;
    private byte percent;

    public Discount(String code, byte percent) {
        this.code = code;
        this.percent = percent;
    }

    public Discount() {

    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public byte getPercent() {
        return percent;
    }

    public void setPercent(byte percent) {
        this.percent = percent;
    }
}

src/main/java/pl/pb/shop_cli/model/OrderState.java
package pl.pb.shop_cli.model;

public enum OrderState {
    UNPAID,
    PREPARING,
    SENT,
    DELIVERED,
    CANCALLED;

    OrderState(){}

    public String getTransation() {
        switch (this) {
            case UNPAID:
                return "Nieopłacone";
            case PREPARING:
                return "W trakcie realizacji";
            case SENT:
                return "Wysłane";
            case DELIVERED:
                return "Doręczone";
            case CANCALLED:
                return "Anulowane";
            default:
                return null;
        }
    }
}

src/main/java/pl/pb/shop_cli/controller/BasketController.java
package pl.pb.shop_cli.controller;

import pl.pb.shop_cli.Credentials;
import pl.pb.shop_cli.model.*;
import pl.pb.shop_cli.service.BasketService;
import pl.pb.shop_cli.service.OrderService;
import pl.pb.shop_cli.service.ProductService;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.ws.rs.core.Response;
import java.io.IOException;
import java.io.Serializable;
import java.math.BigDecimal;

import static pl.pb.shop_cli.Constants.APP_NAME;

@Named
@ViewScoped
public class BasketController implements Serializable {
    @EJB
    private BasketService basketService;
    @EJB
    private ProductService productService;
    @EJB
    private OrderService orderService;
    private Basket basket;
    private ProductBasket editedProductBasket;
    private Long previousAmount;
    private String discountCode;

    public Basket getBasket() {
        return basket;
    }

    public ProductBasket getEditedProductBasket() {
        return editedProductBasket;
    }

    public String getDiscountCode() {
        return discountCode;
    }

    public void setDiscountCode(String discountCode) {
        this.discountCode = discountCode;
    }

    public boolean isBasketEmpty() {
        return basket.getProductBaskets().size() < 1;
    }

    public BigDecimal getTotalBasketPrice() {
        BigDecimal totalPrice = new BigDecimal(0);
        for(ProductBasket product : basket.getProductBaskets())
            totalPrice = totalPrice.add(product.getTotalPrice());

        return totalPrice;
    }

    public BigDecimal getDiscountSize() {
        return getTotalBasketPrice().multiply(new BigDecimal(basket.getDiscount().getPercent())).divide(new BigDecimal(100));
    }

    public BigDecimal getTotalBasketPriceWithDiscount() {
        return getTotalBasketPrice().subtract(getDiscountSize());
    }

    @PostConstruct
    public void initBasket() {
        basket = basketService.getBasket(Credentials.Token);
    }

    public void onRemoveProduct(ProductBasket productBasket) {
        basket.getProductBaskets().remove(productBasket);
        basketService.removeProduct(productBasket.getProduct().getId(), Credentials.Token);
        Product product = productBasket.getProduct();
        product.setAmount(product.getAmount() + productBasket.getAmount());
        productService.save(product, Credentials.Token);
    }

    public void onClearBasket() {
        for(ProductBasket productBasket : basket.getProductBaskets()) {
            Product product = productBasket.getProduct();
            product.setAmount(product.getAmount() + productBasket.getAmount());
            productService.save(product, Credentials.Token);
        }

        basketService.clearBasket(Credentials.Token);
        basket.clearBasket();
    }

    public void onEditProduct(ProductBasket productBasket) {
        editedProductBasket = productBasket;
        previousAmount = productBasket.getAmount();
    }

    public void onSaveEdit() {
        if(editedProductBasket.getAmount() < 1) {
            editedProductBasket.setAmount(previousAmount);
            FacesContext.getCurrentInstance().validationFailed();
            FacesContext.getCurrentInstance().addMessage("amountError", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                    "Liczba produktów nie może być mniejsza od jeden!"));
            return;
        }

        if(previousAmount != editedProductBasket.getAmount()) {
            Response response = basketService.changeProductAmount(
                    new ProductAmount(editedProductBasket.getProduct().getId(), editedProductBasket.getAmount()), Credentials.Token);

            if(response.getStatusInfo().equals(Response.Status.NO_CONTENT)) {
                FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Zaktualizowano koszyk",
                        "Pomyślnie zaktualizowano zawartość koszyka"));
            } else {
                editedProductBasket.setAmount(previousAmount);
                FacesContext.getCurrentInstance().validationFailed();
                FacesContext.getCurrentInstance().addMessage("amountError", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                        "Niewystraczająca liczba produktów na stanie!"));
                return;
            }
        }

        editedProductBasket = null;
    }

    public void onCancelEdit() {
        editedProductBasket = null;
    }

    public void onApplyDiscount() {
        Response response = basketService.addDiscount(discountCode, Credentials.Token);
        if(response.getStatus() != 400) {
            initBasket();
        } else {
            FacesContext.getCurrentInstance().validationFailed();
            FacesContext.getCurrentInstance().addMessage("discountError", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                    "Nieprawidłowy kod rabatowy"));
        }
    }

    public void onRemoveDiscount() {
        basket.setDiscount(null);
        basketService.removeDiscount(Credentials.Token);
    }

    public void onSubmitOrder() throws IOException {
        Response response = orderService.submitOrder(Credentials.Token);
        if(response.getStatusInfo().equals(Response.Status.NO_CONTENT))
            FacesContext.getCurrentInstance().getExternalContext().redirect(APP_NAME + "pages/my-orders.xhtml");
        else
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                    "Podczas składania zamówienia wystąpił błąd"));
    }
}

src/main/java/pl/pb/shop_cli/controller/DiscountController.java
package pl.pb.shop_cli.controller;

import pl.pb.shop_cli.Credentials;
import pl.pb.shop_cli.model.Discount;
import pl.pb.shop_cli.service.DiscountService;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

@Named
@ViewScoped
public class DiscountController implements Serializable {
    @EJB
    private DiscountService discountService;
    private List<Discount> discounts;
    private Discount editedDiscount;
    private byte previousPercent;

    public List<Discount> getDiscounts() {
        return discounts;
    }

    public Discount getEditedDiscount() {
        return editedDiscount;
    }

    @PostConstruct
    private void findAll() {
        discounts = discountService.findAll(Credentials.Token);
    }

    public void onEditDiscount(Discount discount) {
        editedDiscount = discount;
        previousPercent = editedDiscount.getPercent();
    }

    public void onRemoveDiscount(Discount discount) {
        discounts.remove(discount);
        discountService.remove(discount, Credentials.Token);
    }

    public void onAddDiscount() {
        editedDiscount = new Discount();
    }

    public void onSaveDiscount() {
        if(editedDiscount.getPercent() <= 0 || editedDiscount.getPercent() >= 100) {
            editedDiscount.setPercent(previousPercent);
            FacesContext.getCurrentInstance().validationFailed();
            FacesContext.getCurrentInstance().addMessage("amountError", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                    "Procent rabatu musi być większy od 0 i mniejszy od 100"));
            return;
        }

        Discount newDiscount = discountService.save(editedDiscount, Credentials.Token);
        if(newDiscount == null) {
            FacesContext.getCurrentInstance().validationFailed();
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                    "Zniżka z takim kodem już istnieje"));
            return;
        }

        if(editedDiscount.getId() == null)
            discounts.add(newDiscount);
        else
            discounts.replaceAll(p -> p != editedDiscount ? p : newDiscount);

        editedDiscount = null;
        FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Dodany zniżkę",
                "Pomyślnie dodano kod rabatowy"));
    }

    public void onCancelDiscount() {
        editedDiscount = null;
    }
}

src/main/java/pl/pb/shop_cli/controller/OrderController.java
package pl.pb.shop_cli.controller;

import pl.pb.shop_cli.Credentials;
import pl.pb.shop_cli.model.OrderState;
import pl.pb.shop_cli.model.ShopOrder;
import pl.pb.shop_cli.model.User;
import pl.pb.shop_cli.service.OrderService;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.ws.rs.core.Response;
import java.io.Serializable;
import java.util.List;

@Named
@ViewScoped
public class OrderController implements Serializable {
    @EJB
    private OrderService orderService;
    private List<ShopOrder> allOrders;
    private List<ShopOrder> myOrders;
    private ShopOrder selectedOrder;

    public List<ShopOrder> getAllOrders() {
        return allOrders;
    }

    public List<ShopOrder> getMyOrders() {
        return myOrders;
    }

    public ShopOrder getSelectedOrder() {
        return selectedOrder;
    }

    public OrderState[] getOrderStates() {
        return OrderState.values();
    }

    @PostConstruct
    public void findOrders() {
        allOrders = orderService.findAllOrders(Credentials.Token);
        myOrders = orderService.findMyOrders(Credentials.Token);
    }

    public void onShowProducts(ShopOrder order) {
        selectedOrder = order;
    }

    public void onCloseProducts() {
        selectedOrder = null;
    }

    public void onPayOrder(ShopOrder order) {
        Response response = orderService.payOrder(order, Credentials.Token);
        if(response.getStatusInfo().equals(Response.Status.NO_CONTENT)) {
            order.setOrderState(OrderState.PREPARING);
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Opłacono zamówienie",
                    "Pomyślnie opłacono zamówienie #" + order.getId()));
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                    "Błąd podczas opłacania zamówienia #" + order.getId()));
        }
    }

    public void onCancelOrder(ShopOrder order) {
        Response response = orderService.setOrderState(order, OrderState.CANCALLED, Credentials.Token);
        if(response.getStatusInfo().equals(Response.Status.NO_CONTENT)) {
            order.setOrderState(OrderState.CANCALLED);
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Anulowano zamówienie",
                    "Pomyślnie anulowano zamówienie #" + order.getId()));
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                    "Błąd podczas anulowania zamówienia #" + order.getId()));
        }
    }

    public void onStatusChanged(ValueChangeEvent event) {
        ShopOrder order = (ShopOrder) ((UIInput) event.getSource()).getAttributes().get("order");
        Response response = orderService.setOrderState(order, (OrderState) event.getNewValue(), Credentials.Token);
        if(response.getStatusInfo().equals(Response.Status.NO_CONTENT)) {
            order.setOrderState(OrderState.CANCALLED);
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Zmiana status zamówienia",
                    "Pomyślnie zmieniono status zamówienia #" + order.getId()));
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Błąd",
                    "Błąd zmiany statusu zamówienia #" + order.getId()));
        }
    }
}

src/main/java/pl/pb/shop_cli/controller/UserController.java
package pl.pb.shop_cli.controller;

import pl.pb.shop_cli.Credentials;
import pl.pb.shop_cli.model.RegisterUser;
import pl.pb.shop_cli.model.User;
import pl.pb.shop_cli.model.UserRole;
import pl.pb.shop_cli.service.UserService;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.ws.rs.core.Response;
import java.io.IOException;
import java.io.Serializable;

import static pl.pb.shop_cli.Constants.APP_NAME;

@Named
@ViewScoped
public class UserController implements Serializable {
    @EJB
    private UserService userService;
    private RegisterUser registerUser;

    public User getCurrentUser() {
        return Credentials.CurrentUser;
    }

    public RegisterUser getRegisterUser() {
        return registerUser;
    }

    public boolean isLogged() {
        return Credentials.CurrentUser != null;
    }

    public boolean isAdmin() {
        if(Credentials.CurrentUser == null || Credentials.CurrentUser.getUserRole() != UserRole.ADMIN)
            return false;

        return true;
    }

    public void onLogin() {
        Credentials.CurrentUser = new User();
    }

    public void onRegister() {
        registerUser = new RegisterUser();
        registerUser.setUserRole(UserRole.CLIENT);
    }

    public void onLogout() throws IOException {
        Credentials.CurrentUser = null;
        Credentials.Token = null;
        FacesContext.getCurrentInstance().getExternalContext().redirect(APP_NAME);
    }

    public void onCheckAuth() throws IOException {
        Response response = userService.login(Credentials.CurrentUser);

        if(response.getStatus() == 200) {
            Credentials.Token = response.getHeaderString("token");
            Credentials.CurrentUser = userService.getMe(Credentials.Token);
            FacesContext.getCurrentInstance().getExternalContext().redirect(APP_NAME);
        } else {
            FacesContext.getCurrentInstance().validationFailed();
        }
    }

    public void onRegisterAuth() {
        if(!registerUser.getPassword().equals(registerUser.getRepeatPassword())) {
            FacesContext.getCurrentInstance().validationFailed();
            return;
        }

        Response response = userService.register(registerUser);
        if(response.getStatus() != 200)
            FacesContext.getCurrentInstance().validationFailed();
    }

    public void onCancelLogin() {
        Credentials.CurrentUser = null;
        Credentials.Token = null;
    }
}

src/main/webapp/pages/all-orders.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>Java Shop - produkty</title>
    <h:outputStylesheet name="css/app.css"/>
</h:head>
<h:body>
    <ui:composition template="/templates/template.xhtml">
        <ui:define name="content">
            <div style="padding: 1em">
                <h:form id="mainForm">
                    <p:growl id="growl" showDetail="true" showSummary="false" keepAlive=""/>

                    <p:dataTable id="productTable" value="#{orderController.allOrders}" var="order" rowKey="#{order.id}"
                                 emptyMessage="Brak zamówień"
                                 paginator="true"
                                 paginatorAlwaysVisible = "false"
                                 paginatorPosition="bottom"
                                 paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                                 rows="10"
                                 rowsPerPageTemplate="10" >
                        <f:facet name="header">
                            Wszystkie zamówienia
                        </f:facet>
                        <p:column headerText="Identyfikator" >
                            #{order.id}
                        </p:column>
                        <p:column headerText="Stan">
                            #{order.orderState.transation}
                        </p:column>
                        <p:column headerText="Całkowita kwota [zł]" >
                            <h:outputText value="#{order.totalPrice}">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                        </p:column>
                        <p:column headerText="Procent zniżki [%]" >
                            <h:panelGroup rendered="#{order.discount == null}">
                                Nie dotyczy
                            </h:panelGroup>
                            <h:outputText value="#{order.discount.percent}">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                        </p:column>
                        <p:column headerText="Produkty" width="100" style="text-align: center">
                            <p:commandButton value="Pokaż" action="#{orderController.onShowProducts(order)}" process="@this" update=":orderDlg" oncomplete="PF('orderDlg').show()"/>
                        </p:column>
                        <p:column headerText="Zmień status" width="175">
                            <p:selectOneMenu id="type" value="#{order.orderState}" valueChangeListener="#{orderController.onStatusChanged}" onchange="submit()">
                                <f:attribute name="order" value="#{order}" />
                                <f:selectItems value="#{orderController.orderStates}" var="type" itemValue="#{type}" itemLabel="#{type.transation}"/>
                            </p:selectOneMenu>
                        </p:column>
                    </p:dataTable>
                </h:form>
            </div>
            <p:dialog id="orderDlg" widgetVar="orderDlg" dynamic="true" header="Zamówienie ##{orderController.selectedOrder.id}" showEffect="fade" hideEffect="fade" width="60%">
                <h:form id="orderDlgForm" >

                    <p:dataTable id="productsTable" value="#{orderController.selectedOrder.productOrders}" var="productOrder" rowKey="#{productOrder.id}"
                                 paginator="true"
                                 paginatorAlwaysVisible = "false"
                                 paginatorPosition="bottom"
                                 paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                                 rows="10"
                                 rowsPerPageTemplate="10" >
                        <f:facet name="header">
                            Zamówione produkty
                        </f:facet>
                        <p:column headerText="Nazwa" >
                            #{productOrder.product.name}
                        </p:column>
                        <p:column headerText="Cena/szt [zł]" >
                            <h:outputText value="#{productOrder.product.price}">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                        </p:column>
                        <p:column headerText="Ilość">
                            #{productOrder.amount}
                        </p:column>
                        <p:column headerText="Całkowita cena [zł]" >
                            <h:outputText value="#{productOrder.totalPrice}">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                        </p:column>
                        <p:column headerText="Zdjęcie" height="75" width="75">
                            <img alt="zdjęcie" src="#{productOrder.product.pictureUrl}" height="75" width="75"/>
                        </p:column>
                    </p:dataTable>

                    <p:commandButton value="Zamknij" action="#{orderController.onCloseProducts()}" process="@this" oncomplete="PF('orderDlg').hide()" style="margin-top: 10px;"/>
                </h:form>
            </p:dialog>
            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" header="Potwierdzenie" >
                <p:commandButton value="Tak" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check" />
                <p:commandButton value="Nie" type="button" styleClass="ui-confirmdialog-no" icon="pi pi-times" style="margin-left: 20px; margin-top: 10px;"/>
            </p:confirmDialog>
        </ui:define>
    </ui:composition>
</h:body>

</html>

src/main/webapp/pages/basket.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <title>Java Shop - koszyk</title>
    <h:outputStylesheet name="css/app.css"/>
</h:head>
<h:body>
    <ui:composition template="/templates/template.xhtml">
        <ui:define name="content">
            <div style="padding: 1em">
                <h:form id="mainForm">
                    <p:growl id="growl" showDetail="true" showSummary="false" keepAlive=""/>

                    <p:dataTable id="productTable" value="#{basketController.basket.productBaskets}" var="productBasket" rowKey="#{productBasket.id}"
                                 emptyMessage="Koszyk jest pusty"
                                 paginator="true"
                                 paginatorAlwaysVisible = "false"
                                 paginatorPosition="bottom"
                                 paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
                                 rows="10"
                                 rowsPerPageTemplate="10" >
                        <f:facet name="header">
                            Zawartość koszyka
                        </f:facet>
                        <p:column headerText="Nazwa" >
                            #{productBasket.product.name}
                        </p:column>
                        <p:column headerText="Opis" >
                            #{productBasket.product.description}
                        </p:column>
                        <p:column headerText="Cena/szt [zł]" >
                            <h:outputText value="#{productBasket.product.price}">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                        </p:column>
                        <p:column headerText="Ilość">
                            #{productBasket.amount}
                        </p:column>
                        <p:column headerText="Cena [zł]" >
                            <h:outputText value="#{productBasket.totalPrice}">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                        </p:column>
                        <p:column headerText="Zdjęcie" height="75" width="75">
                            <img alt="zdjęcie" src="#{productBasket.product.pictureUrl}" height="75" width="75"/>
                        </p:column>
                        <p:column headerText="Edytuj" width="80" style="text-align: center">
                            <p:commandButton icon="fa fa-fw fa-edit"  title="Edytuj" action="#{basketController.onEditProduct(productBasket)}" process="@this" update=":productDlg" oncomplete="PF('productDlg').show()" />
                        </p:column>
                        <p:column headerText="Usuń" width="80" style="text-align: center">
                            <p:commandButton icon="fa fa-fw fa-remove" title="Usuń" action="#{basketController.onRemoveProduct(productBasket)}" process="@this" update=":mainForm:productTable" >
                                <p:confirm message="Czy chcesz usunąć ten produkt z koszyka?" icon="pi pi-exclamation-triangle" />
                            </p:commandButton>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton icon="fa fa-fw fa-remove" value="Wyczyść koszyk" title="Usuń" action="#{basketController.onClearBasket()}" process="@this" update=":mainForm:productTable" style="display:#{(basketController.basketEmpty)?'none':'inline-block'}; text-align: left; margin-top: 7px">
                                <p:confirm message="Czy chcesz wyczyścić koszyk?" icon="pi pi-exclamation-triangle" />
                            </p:commandButton>
                            <div style="text-align: right; margin-top: #{(basketController.basketEmpty)?'0':'-42px'}">
                                <p>
                                    Całkowita suma zamówienia:
                                    <h:outputText value="#{basketController.totalBasketPrice}">
                                        <f:convertNumber pattern="#0.00"/>
                                    </h:outputText>
                                    zł
                                </p>
                            </div>
                        </f:facet>
                    </p:dataTable>
                </h:form>
                <h:form id="discountForm" style="padding-top: 1em">
                    <h:panelGrid columns="4">
                        <p:outputLabel value="Kod rabatowy" for="@next"/>
                        <p:inputText id="discount" value="#{basketController.discountCode}" required="true" requiredMessage="Podaj kod rabatowy"/>
                        <p:commandButton value="Zastosuj kod" action="#{basketController.onApplyDiscount()}" process="@form" update=":discountForm :mainForm" style="margin-left: 10px; margin-right: 10px"/>
                        <p:commandButton icon="fa fa-fw fa-remove" value="Usuń kod" action="#{basketController.onRemoveDiscount()}" process="@this" update=":discountForm" rendered="#{basketController.basket.discount != null}" style="background-color: #cc0000; border-color: #cc0000">
                            <p:resetInput target=":discountForm"/>
                        </p:commandButton>
                    </h:panelGrid>

                    <h:panelGroup id="summaryInfo" rendered="#{basketController.basket.discount != null}">
                        <p>Aktywowany kod: #{basketController.basket.discount.code}, rabat: #{basketController.basket.discount.percent}%</p>
                        <p>Kwota rabatu:
                            <h:outputText value="#{basketController.discountSize}">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                            zł
                        </p>
                        <p>Całkowita kwota zamówienia po rabacie:
                            <h:outputText value="#{basketController.totalBasketPriceWithDiscount}">
                                <f:convertNumber pattern="#0.00"/>
                            </h:outputText>
                            zł
                        </p>
                    </h:panelGroup>
                </h:form>
                <h:form id="submitOrderForm" style="padding-top: 1em" rendered="#{!basketController.basketEmpty}">
                    <p:commandButton value="Złóż zamówienie" action="#{basketController.onSubmitOrder()}" process="@form" style="background-color: green; border-color: green"/>
                </h:form>
            </div>
            <p:dialog id="productDlg" widgetVar="productDlg" dynamic="true" header="Produkt" showEffect="fade" hideEffect="fade">
                <h:form id="productDlgForm" >

                    <h:panelGrid columns="2">
                        <p:outputLabel value="Nazwa" for="@next"/>
                        <p:inputText id="name" value="#{basketController.editedProductBasket.product.name}" disabled="true"/>
                        <p:outputLabel value="Cena/szt [zł]" for="@next"/>
                        <p:inputText id="price" value="#{basketController.editedProductBasket.product.price}" disabled="true"/>
                        <p:outputLabel value="Ilość" for="@next"/>
                        <p:inputText id="amount" value="#{basketController.editedProductBasket.amount}" required="true"/>
                        <h:message class="error" for="amount" id="amountError"/>
                    </h:panelGrid>

                    <p:commandButton value="Zapisz" action="#{basketController.onSaveEdit()}" process="@form" update=":mainForm :discountForm" oncomplete="if (args &amp;&amp; !args.validationFailed) PF('productDlg').hide()"  />
                    <p:commandButton  value="Anuluj" action="#{basketController.onCancelEdit()}" process="@this" update=":mainForm:growl" oncomplete="PF('productDlg').hide()" style="margin-left: 20px; margin-top: 10px;">
                        <p:resetInput target=":productDlgForm"/>
                    </p:commandButton>
                </h:form>
            </p:dialog>
            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" header="Potwierdzenie" >
                <p:commandButton value="Tak" type="button" styleClass="ui-confirmdialog-yes" icon="pi pi-check" />
                <p:commandButton value="Nie" type="button" styleClass="ui-confirmdialog-no" icon="pi pi-times" style="margin-left: 20px; margin-top: 10px;"/>
            </p:confirmDialog>
        </ui:define>
    </ui:composition>
</h:body>

</html>