src/main/java/pl/pb/shop_cli/controller/UserController.java
package pl.pb.shop_cli.controller;

import pl.pb.shop_cli.Credentials;
import pl.pb.shop_cli.model.RegisterUser;
import pl.pb.shop_cli.model.User;
import pl.pb.shop_cli.model.UserRole;
import pl.pb.shop_cli.service.UserService;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.ws.rs.core.Response;
import java.io.IOException;
import java.io.Serializable;

import static pl.pb.shop_cli.Constants.APP_NAME;

@Named
@ViewScoped
public class UserController implements Serializable {
    @EJB
    private UserService userService;
    private RegisterUser registerUser;

    public User getCurrentUser() {
        return Credentials.CurrentUser;
    }

    public RegisterUser getRegisterUser() {
        return registerUser;
    }

    public boolean isLogged() {
        return Credentials.CurrentUser != null;
    }

    public boolean isAdmin() {
        if(Credentials.CurrentUser == null || Credentials.CurrentUser.getUserRole() != UserRole.ADMIN)
            return false;

        return true;
    }

    public void onLogin() {
        Credentials.CurrentUser = new User();
    }

    public void onRegister() {
        registerUser = new RegisterUser();
        registerUser.setUserRole(UserRole.CLIENT);
    }

    public void onLogout() throws IOException {
        Credentials.CurrentUser = null;
        Credentials.Token = null;
        FacesContext.getCurrentInstance().getExternalContext().redirect(APP_NAME);
    }

    public void onCheckAuth() throws IOException {
        Response response = userService.login(Credentials.CurrentUser);

        if(response.getStatus() == 200) {
            Credentials.Token = response.getHeaderString("token");
            Credentials.CurrentUser = userService.getMe(Credentials.Token);
            FacesContext.getCurrentInstance().getExternalContext().redirect(APP_NAME);
        } else {
            FacesContext.getCurrentInstance().validationFailed();
        }
    }

    public void onRegisterAuth() {
        if(!registerUser.getPassword().equals(registerUser.getRepeatPassword())) {
            FacesContext.getCurrentInstance().validationFailed();
            return;
        }

        Response response = userService.register(registerUser);
        if(response.getStatus() != 200)
            FacesContext.getCurrentInstance().validationFailed();
    }

    public void onCancelLogin() {
        Credentials.CurrentUser = null;
        Credentials.Token = null;
    }
}

src/main/webapp/templates/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions">
<h:head>
    <title>Java Shop</title>
    <h:outputStylesheet name="css/app.css"/>
</h:head>
<h:body>
    <pe:layout fullPage="true" resizeTitle="resize" style="background-color: #FFFFFF;">
        <pe:layoutPane position="north" resizable="false" id="north" closable="false">
            <ui:insert name="header">
                <h:form id="headerForm">
                    <div style="background-color: #FF9933; padding: 0.5em">
                        <h2 style="display: inline-block; margin-left: 20px">Java Shop</h2>
                        <p:commandButton value="Zaloguj się" action="#{userController.onLogin()}" process="@this" update=":loginDlg" oncomplete="PF('loginDlg').show()" style="display:#{(userController.logged)?'none':'inline-block'}; float: right; margin-top: 20px; margin-left: 20px"/>
                        <p:commandButton value="Zarejestruj się" action="#{userController.onRegister()}" process="@this" update=":registerDlg" oncomplete="PF('registerDlg').show()" style="margin-left: 20px; display:#{(userController.logged)?'none':'inline-block'}; float: right; margin-top: 20px;"/>
                        <p:commandButton value="Wyloguj się" action="#{userController.onLogout()}" style="display:#{(userController.logged)?'inline-block':'none'}; float: right; margin-top: 20px"/>
                        <p:commandButton value="Witaj, #{userController.currentUser.name}" style="display:#{(userController.logged)?'inline-block':'none'}; float: right; margin-right: 20px; margin-top: 20px"/>
                    </div>
                </h:form>
            </ui:insert>
        </pe:layoutPane >

        <pe:layoutPane  position="west" id="west" header="Menu" style="height:580px;overflow:hidden;" size="225">
            <div style="display:#{(userController.logged)?'block':'none'}">
                <ui:include src="/include/menu.xhtml"/>
            </div>
        </pe:layoutPane >

        <pe:layoutPane styleClass="layoutUnitCenter" position="center" closable="false">
            <ui:insert name="content" id="testId">content placeholder</ui:insert>
        </pe:layoutPane >

        <pe:layoutPane position="south" id="south" closable="false" resizable="false">
            <div style="text-align: center; background-color: #FF9933; padding: 1em">
                <ui:insert name="footer">
                    Szymon Zawadzki, Piotr Wyszyński
                </ui:insert>
            </div>
        </pe:layoutPane >
    </pe:layout>
    <p:dialog id="loginDlg" widgetVar="loginDlg" dynamic="true" header="Zaloguj się" showEffect="fade" hideEffect="fade">
        <h:form id="loginDlgForm" >

            <h:panelGrid columns="2">
                <p:outputLabel value="Email" for="@next"/>
                <p:inputText id="email" value="#{userController.currentUser.email}" required="true"/>
                <p:outputLabel value="Hasło" for="@next"/>
                <p:password id="password" value="#{userController.currentUser.password}" required="true"/>
            </h:panelGrid>

            <p:commandButton value="Zaloguj się" action="#{userController.onCheckAuth()}" process="@form" oncomplete="if (args &amp;&amp; !args.validationFailed) PF('loginDlg').hide()"/>
            <p:commandButton value="Anuluj" action="#{userController.onCancelLogin()}" process="@this" oncomplete="PF('loginDlg').hide()" style="margin-left: 20px; margin-top: 10px;">
                <p:resetInput target=":loginDlgForm"/>
            </p:commandButton>
        </h:form>
    </p:dialog>
    <p:dialog id="registerDlg" widgetVar="registerDlg" dynamic="true" header="Zarejestruj się" showEffect="fade" hideEffect="fade">
        <h:form id="registerDlgForm" >

            <h:panelGrid columns="2">
                <p:outputLabel value="Email" for="@next"/>
                <p:inputText id="register-email" value="#{userController.registerUser.email}" required="true"/>
                <p:outputLabel value="Hasło" for="@next"/>
                <p:password id="register-password" value="#{userController.registerUser.password}" required="true"/>
                <p:outputLabel value="Powtórz hasło" for="@next"/>
                <p:password id="register-password-2" value="#{userController.registerUser.repeatPassword}" required="true"/>
                <p:outputLabel value="Imię" for="@next"/>
                <p:inputText id="name" value="#{userController.registerUser.name}" required="true"/>
                <p:outputLabel value="Nazwisko" for="@next"/>
                <p:inputText id="surname" value="#{userController.registerUser.surname}" required="true"/>
                <p:outputLabel value="Adres" for="@next"/>
                <p:inputText id="address" value="#{userController.registerUser.address}" required="true"/>
            </h:panelGrid>

            <p:commandButton value="Zarejestruj się" action="#{userController.onRegisterAuth()}" process="@form" oncomplete="if (args &amp;&amp; !args.validationFailed) PF('registerDlg').hide()"  />
            <p:commandButton value="Anuluj" action="#{userController.onCancelLogin()}" process="@this" oncomplete="PF('registerDlg').hide()" style="margin-left: 20px; margin-top: 10px;">
                <p:resetInput target=":registerDlgForm"/>
            </p:commandButton>
        </h:form>
    </p:dialog>
</h:body>

</html>